# .github/release.yml

changelog:
    exclude:
        labels:
            - ignore-for-release
        authors:
            - octocat
    categories:
        - title: Exciting New Features 🎉
          labels:
              - "*"
        - title: Bug Fixes 🛠
          labels:
              - "*"
        - title: Other Changes 🔧
          labels:
              - "*"